version: "5.8"
servers:
  - id: default
    transport: mx
transportgroups:
  - id: default
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
          notify: true
        - interval: 7200
        - interval: 10800
    dsn:
      transport: mx
    transports:
      - id: mx
        session:
          tls:
            mode: dane
resolver:
  cache:
    size: 10000
